export const assignments = [
  {
    engineerEmail: "alice@example.com",
    projectName: "AI Dashboard",
    allocationPercentage: 50,
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-09-30"),
    role: "Frontend Developer",
  },
  {
    engineerEmail: "alice@example.com",
    projectName: "Client Portal",
    allocationPercentage: 50,
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-10-01"),
    role: "React Engineer",
  },
  {
    engineerEmail: "raj@example.com",
    projectName: "API Integration Layer",
    allocationPercentage: 50,
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-07-15"),
    role: "Python Developer",
  },
  {
    engineerEmail: "sarah@example.com",
    projectName: "AI Dashboard",
    allocationPercentage: 60,
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-09-30"),
    role: "React Developer",
  },
  {
    engineerEmail: "dev@example.com",
    projectName: "Backend Revamp",
    allocationPercentage: 50,
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-10-15"),
    role: "Node.js Engineer",
  },
  {
    engineerEmail: "sarah@example.com",
    projectName: "Client Portal",
    allocationPercentage: 40,
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-10-01"),
    role: "Frontend Support",
  },
];
