export const users = [
  {
    name: "Alice Kumar",
    email: "alice@example.com",
    password: "password123",
    role: "engineer",
    skills: ["React", "Node.js"],
    seniority: "mid",
    maxCapacity: 100,
    department: "Frontend",
  },
  {
    name: "Raj Patel",
    email: "raj@example.com",
    password: "password123",
    role: "engineer",
    skills: ["Python", "Django"],
    seniority: "senior",
    maxCapacity: 50,
    department: "Backend",
  },
  {
    name: "Sarah Lee",
    email: "sarah@example.com",
    password: "password123",
    role: "engineer",
    skills: ["React", "TypeScript"],
    seniority: "junior",
    maxCapacity: 100,
    department: "Frontend",
  },
  {
    name: "Dev Singh",
    email: "dev@example.com",
    password: "password123",
    role: "engineer",
    skills: ["Node.js", "MongoDB", "TypeScript"],
    seniority: "mid",
    maxCapacity: 50,
    department: "Backend",
  },
  {
    name: "Manager Reddy",
    email: "manager@example.com",
    password: "admin123",
    role: "manager",
    skills: [],
    seniority: "senior",
    maxCapacity: 0,
    department: "Management",
  },
];
